# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
---
Master:
  HttpPort: 8080
  SlavePort: 50000

Deployment:
  RegistryKeyName: myregistrykey
  # Image value can be from ECR or Docker Hub, see README for further instructions
  Image: yourAccountNumber.dkr.ecr.yourRegion.amazonaws.com/yourRepoName
  Tag: latest
  PullPolicy: Always
