---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  ports:
    - name: "www"
      port: {{ .Values.Master.HttpPort }}
      targetPort: {{ .Values.Master.HttpPort }}
    - name: "slaveport"
      port: {{ .Values.Master.SlavePort }}
      targetPort: {{ .Values.Master.SlavePort }}
  selector:
    run: jenkins-service
  type: NodePort
